### ISSUE TITLE
construct gregorian calendar and convert it to persian calendar

### ISSUE THREAD

**Issue by moeintav** [chrisengelsma/almanac-converter#15]
Hi I am moein and develope android app for calendar view pager . thank you for your classes. I want to construct gregorian calendar from current time and convert it to persian calendar and Islamic calendar
how do you this? sorry for bad english

**Comment by chrisengelsma** [comment]
Hi @moeintav ! One way to convert a gregorian calendar would be to create a new object for each calendar and pass in the gregorian calendar as the parameters.

`
GregorianCalendar gregorianCal = new GregorianCalendar()
IslamicCalendar islamicCal = new IslamicCalendar(cal)
PersianCalendar persianCal = new PersianCalendar(cal)
`

Note that the calendars are not coupled and need to be updated independently.

**Comment by chrisengelsma** [comment]
I just realized that you might be referring to a `java.util.Calendar` in which case I haven't extended the Persian or Islamic calendars to natively support yet, but I can add that as a task.

**Comment by moeintav** [comment]
Thank you very much
Note that the calendars are not coupled and need to be updated independently? what is this i am not understood

**Comment by chrisengelsma** [comment]
What I mean is that each calendar needs to be updated independently. So if you change the date on the Gregorian Calendar, it will not automatically update the Islamic or Persian calendar and each calendar must be updated independently. 

For example,

```java
gregorianCalendar.addDays(5);
islamicCalendar.addDays(5);
persianCalendar.addDays(5);
````

**Comment by moeintav** [comment]
Thank you very much
i write your code
GregorianCalendar gregorianCal = new GregorianCalendar();
IslamicCalendar islamicCal = new IslamicCalendar(gregorianCal);
PersianCalendar persianCal = new PersianCalendar(gregorianCal);

and out put is:

Gregorian Calendar: September 12, 2017
Persian Calendar: 21 Shahrivar, 1396
Islamic Calendar: 20 Dhu al-Hijjah, 1438

but today is 21 Dhu al-Hijjah, 1438

**Comment by moeintav** [comment]
Islamic calendar is One day back

**Comment by chrisengelsma** [comment]
Hmmm, it's worth noting that the Islamic calendar is using the Hijri calendar which can differ from Saudi Arabia's Umm al-Qura calendar by +/- 1 day.  I don't have anything built in to handle this yet. 

For now, you can adjust the day manually after constructing it:

```java
islamicCalendar.nextDay();
```

**Comment by chrisengelsma** [comment]
Also worth noting is there are 4 different leap year rules (IslamicCalendar.LeapYearRule):

IslamicCalendar.LeapYearRule.WEST_ISLAM (default)
IslamicCalendar.LeapYearRule.EAST_ISLAM
IslamicCalendar.LeapYearRule.HABASH_AL_HASIB
IslamicCalendar.LeapYearRule.TAIYABI_ISMAILI

Each of these will change the date. I believe in your case, constructing the leap year using the EAST_ISLAM leap year rule will get you the date you expect:

```java
islamicCalendar.setLeapYearRule(IslamicCalendar.LeapYearRule.EAST_ISLAM)
```

Give that a shot

**Comment by moeintav** [comment]
Hi Thank you .
Do you mean?

 Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
        calendar.setTimeZone(TimeZone.getTimeZone("Asia/Tehran"));
        GregorianCalendar gregorianCal = new GregorianCalendar(calendar);
        IslamicCalendar islamicCal = new IslamicCalendar(gregorianCal);
        PersianCalendar persianCal = new PersianCalendar(gregorianCal);

**Comment by moeintav** [comment]
I think I found the solution in Islamic calendar I change the CalendarType to Astronomical and out put is this:
Gregorian Calendar: September 12, 2017
Islamic Calendar: 21 Dhu al-Hijjah, 1438
Persian Calendar: 21 Shahrivar, 1396

**Comment by chrisengelsma** [comment]
Oh wonderful! I'm glad you found that :)

**Comment by moeintav** [comment]
Hi sorry for my question but when I use calendar type astronomical the number ofdays in hejri month 30  and it is work perfectly but 31 shahrivar 1396 is 1 muharram 1439 but Islamic calendar output is 
2 muharram 1439

**Comment by moeintav** [comment]
actually Dhu al-Hijjah 1438 is 30 day and muharram  1439 is start by 2 instaed 1.

**Comment by chrisengelsma** [comment]
Because of all the variations involved with the Islamic calendar (regional, religious, astronomical, civic, etc) this is a tricky one to hunt down. For now, you will have to find the settings that closest suit your needs
